[2022-12-27T06:07:23.927+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bertopic_autopik_airflow.train_vectorizers scheduled__2022-12-27T04:00:00+00:00 [queued]>
[2022-12-27T06:07:23.939+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bertopic_autopik_airflow.train_vectorizers scheduled__2022-12-27T04:00:00+00:00 [queued]>
[2022-12-27T06:07:23.939+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T06:07:23.939+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-27T06:07:23.939+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T06:07:23.960+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): train_vectorizers> on 2022-12-27 04:00:00+00:00
[2022-12-27T06:07:23.973+0000] {standard_task_runner.py:54} INFO - Started process 455 to run task
[2022-12-27T06:07:23.981+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bertopic_autopik_***', 'train_vectorizers', 'scheduled__2022-12-27T04:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/bertopic_autopik_***.py', '--cfg-path', '/tmp/tmp69g7eauf']
[2022-12-27T06:07:23.983+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask train_vectorizers
[2022-12-27T06:07:23.984+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/bertopic_autopik_***.py
[2022-12-27T06:07:35.174+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-27T06:07:35.241+0000] {task_command.py:384} INFO - Running <TaskInstance: bertopic_autopik_airflow.train_vectorizers scheduled__2022-12-27T04:00:00+00:00 [running]> on host c4e9f2234c2b
[2022-12-27T06:07:35.316+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=hojun.seo@pikurate.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bertopic_autopik_***
AIRFLOW_CTX_TASK_ID=train_vectorizers
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-27T04:00:00+00:00
[2022-12-27T06:07:38.998+0000] {logging_mixin.py:117} INFO - It is pandas.Series type
[2022-12-27T06:07:40.526+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/training_vectorizers.py", line 34, in train_vectorizers_save
    count_vectorizer, tfidf_transformer, feature_names = tf_idf(data['link_title'])
  File "/opt/airflow/dags/functions/training_vectorizers.py", line 25, in tf_idf
    feature_names=cv.get_feature_names()
AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'
[2022-12-27T06:07:40.536+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=bertopic_autopik_***, task_id=train_vectorizers, execution_date=20221227T040000, start_date=20221227T060723, end_date=20221227T060740
[2022-12-27T06:07:40.894+0000] {standard_task_runner.py:102} ERROR - Failed to execute job 11 for task train_vectorizers ('CountVectorizer' object has no attribute 'get_feature_names'; 455)
[2022-12-27T06:07:41.039+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-27T06:07:41.081+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
